apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: adex-webapp-frontend-hpa-stg
  namespace: adex-webapp-stg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adex-webapp-frontend-deployment-stg
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50